In [43]:
import io
import requests
import pandas as pd
import hashlib
from pathlib import Path

data_dir = Path("data")
data_dir.mkdir(exist_ok=True)

In [44]:
resp = requests.get(
    "https://data.cityofchicago.org/resource/u6pd-qa9d.csv",
    params={"$where": "crash_date >= '2021-01-01T00:00:00'", "$limit": 1500000},
    timeout=300
)
df = pd.read_csv(io.StringIO(resp.text), low_memory=False)
print(f"Shape: {df.shape}")
sha256_people = hashlib.sha256(resp.content).hexdigest()
print(f"SHA-256 (People): {sha256_people}")

Shape: (1277363, 29)
SHA-256 (People): 0041a8ade6bc0b71b4fd387d18bcf443c080585cf0776b6c7deb8b395c6573a5

In [45]:
df.head()

,person_id,person_type,crash_record_id,vehicle_id,crash_date,seat_no,city,state,zipcode,sex,...,ems_run_no,driver_action,driver_vision,physical_condition,pedpedal_action,pedpedal_visibility,pedpedal_location,bac_result,bac_result_value,cell_phone_use
0,O2298523,DRIVER,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,2192156.0,2026-05-06T01:26:00.000,NaN,MAYWOOD,IL,60153,F,...,NaN,UNKNOWN,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
1,O2298516,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192153.0,2026-05-06T01:25:00.000,NaN,CHICAGO,IL,60614,M,...,NaN,FAILED TO YIELD,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
2,O2298517,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06T01:25:00.000,NaN,CHICAGO,IL,60617,F,...,NaN,NONE,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
3,P505529,PASSENGER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06T01:25:00.000,3.0,CHICAGO,IL,60620,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,O2298528,DRIVER,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,2192164.0,2026-05-06T00:48:00.000,NaN,CHICAGO,IL,60647,M,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN

In [46]:
df

,person_id,person_type,crash_record_id,vehicle_id,crash_date,seat_no,city,state,zipcode,sex,...,ems_run_no,driver_action,driver_vision,physical_condition,pedpedal_action,pedpedal_visibility,pedpedal_location,bac_result,bac_result_value,cell_phone_use
0,O2298523,DRIVER,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,2192156.0,2026-05-06T01:26:00.000,NaN,MAYWOOD,IL,60153,F,...,NaN,UNKNOWN,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
1,O2298516,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192153.0,2026-05-06T01:25:00.000,NaN,CHICAGO,IL,60614,M,...,NaN,FAILED TO YIELD,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
2,O2298517,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06T01:25:00.000,NaN,CHICAGO,IL,60617,F,...,NaN,NONE,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
3,P505529,PASSENGER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06T01:25:00.000,3.0,CHICAGO,IL,60620,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,O2298528,DRIVER,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,2192164.0,2026-05-06T00:48:00.000,NaN,CHICAGO,IL,60647,M,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277358,P230379,PASSENGER,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,964731.0,2021-01-01T00:05:00.000,3.0,NaN,NaN,NaN,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1277359,O1017884,DRIVER,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,964732.0,2021-01-01T00:04:00.000,NaN,NaN,NaN,NaN,X,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
1277360,O1019428,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966223.0,2021-01-01T00:00:00.000,NaN,CHICAGO,IL,60618,M,...,NaN,UNKNOWN,UNKNOWN,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
1277361,O1019429,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01T00:00:00.000,NaN,CICERO,IL,60804,F,...,NaN,NONE,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
1277362,P230706,PASSENGER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01T00:00:00.000,3.0,CHICAGO,IL,NaN,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
print(f"Shape: {df.shape}")
df.describe(include="number").T

Shape: (1277363, 29)

,count,mean,std,min,25%,50%,75%,max
vehicle_id,1249456.0,1.579833e+06,353120.723415,964727.0,1274529.50,1579136.50,1884601.25,2192166.0
seat_no,253287.0,4.159084e+00,2.270334,1.0,3.00,3.00,5.00,12.0
age,900951.0,3.804931e+01,17.048326,-59.0,26.00,35.00,50.00,110.0
bac_result_value,1180.0,1.772966e-01,0.101964,0.0,0.14,0.18,0.22,1.0

In [48]:
df[["injury_classification", "person_type"]].value_counts().head(20)

injury_classification     person_type
NO INDICATION OF INJURY   DRIVER               926475
                          PASSENGER            218084
NONINCAPACITATING INJURY  DRIVER                37646
REPORTED, NOT EVIDENT     DRIVER                26413
NONINCAPACITATING INJURY  PASSENGER             18360
REPORTED, NOT EVIDENT     PASSENGER             14188
NONINCAPACITATING INJURY  PEDESTRIAN             8497
INCAPACITATING INJURY     DRIVER                 5397
NONINCAPACITATING INJURY  BICYCLE                5283
NO INDICATION OF INJURY   BICYCLE                2976
REPORTED, NOT EVIDENT     PEDESTRIAN             2829
INCAPACITATING INJURY     PEDESTRIAN             2389
                          PASSENGER              2314
NO INDICATION OF INJURY   PEDESTRIAN             1900
REPORTED, NOT EVIDENT     BICYCLE                1509
INCAPACITATING INJURY     BICYCLE                 900
NO INDICATION OF INJURY   NON-MOTOR VEHICLE       710
FATAL                     DRIVER                  355
NONINCAPACITATING INJURY  NON-MOTOR VEHICLE       258
FATAL                     PEDESTRIAN              210
Name: count, dtype: int64

In [49]:
df = df.replace(["UNKNOWN", "NONE", ""], pd.NA)

In [50]:
df.isna().mean().sort_values(ascending=False)

cell_phone_use           0.999995
bac_result_value         0.999076
ejection                 0.996822
ems_run_no               0.986474
pedpedal_visibility      0.978769
pedpedal_location        0.978739
pedpedal_action          0.978737
ems_agency               0.923283
hospital                 0.872652
seat_no                  0.801711
driver_action            0.694815
driver_vision            0.635907
drivers_license_class    0.541623
physical_condition       0.491983
drivers_license_state    0.417901
zipcode                  0.329679
age                      0.294679
city                     0.284665
state                    0.267561
bac_result               0.200122
vehicle_id               0.021847
airbag_deployed          0.021117
sex                      0.019028
safety_equipment         0.002585
injury_classification    0.000197
person_type              0.000000
crash_date               0.000000
crash_record_id          0.000000
person_id                0.000000
dtype: float64

In [51]:
df = df.drop(columns=[c for c in df.columns if df[c].isna().mean() > 0.8])

In [52]:
df.isna().mean().sort_values(ascending=False)

driver_action            0.694815
driver_vision            0.635907
drivers_license_class    0.541623
physical_condition       0.491983
drivers_license_state    0.417901
zipcode                  0.329679
age                      0.294679
city                     0.284665
state                    0.267561
bac_result               0.200122
vehicle_id               0.021847
airbag_deployed          0.021117
sex                      0.019028
safety_equipment         0.002585
injury_classification    0.000197
person_type              0.000000
crash_date               0.000000
crash_record_id          0.000000
person_id                0.000000
dtype: float64

In [53]:
df.columns = df.columns.str.lower()

In [54]:
df["crash_record_id"] = df["crash_record_id"].astype(str)

In [55]:
df["crash_date"] = pd.to_datetime(df["crash_date"], errors="coerce")
df

,person_id,person_type,crash_record_id,vehicle_id,crash_date,city,state,zipcode,sex,age,drivers_license_state,drivers_license_class,safety_equipment,airbag_deployed,injury_classification,driver_action,driver_vision,physical_condition,bac_result
0,O2298523,DRIVER,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,2192156.0,2026-05-06 01:26:00,MAYWOOD,IL,60153,F,55.0,IL,AM,USAGE UNKNOWN,NOT APPLICABLE,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
1,O2298516,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192153.0,2026-05-06 01:25:00,CHICAGO,IL,60614,M,21.0,IL,D,USAGE UNKNOWN,NOT APPLICABLE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED
2,O2298517,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60617,F,22.0,IL,D,USAGE UNKNOWN,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
3,P505529,PASSENGER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60620,F,NaN,NaN,NaN,USAGE UNKNOWN,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN
4,O2298528,DRIVER,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,2192164.0,2026-05-06 00:48:00,CHICAGO,IL,60647,M,35.0,IL,D,USAGE UNKNOWN,"DEPLOYED, FRONT","REPORTED, NOT EVIDENT",NaN,NaN,NaN,TEST NOT OFFERED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277358,P230379,PASSENGER,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,964731.0,2021-01-01 00:05:00,NaN,NaN,NaN,M,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN
1277359,O1017884,DRIVER,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,964732.0,2021-01-01 00:04:00,NaN,NaN,NaN,X,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED
1277360,O1019428,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966223.0,2021-01-01 00:00:00,CHICAGO,IL,60618,M,24.0,IL,D,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NORMAL,TEST NOT OFFERED
1277361,O1019429,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CICERO,IL,60804,F,23.0,IL,D,SAFETY BELT USED,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
1277362,P230706,PASSENGER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CHICAGO,IL,NaN,M,24.0,NaN,NaN,SAFETY BELT USED,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN

In [56]:
df["sex"] = df["sex"].str.upper()
df["person_type"] = df["person_type"].str.upper()

In [57]:
df = df.dropna(subset=["crash_date"])
df = df[df["crash_date"] >= "2021-01-01"]
df

,person_id,person_type,crash_record_id,vehicle_id,crash_date,city,state,zipcode,sex,age,drivers_license_state,drivers_license_class,safety_equipment,airbag_deployed,injury_classification,driver_action,driver_vision,physical_condition,bac_result
0,O2298523,DRIVER,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,2192156.0,2026-05-06 01:26:00,MAYWOOD,IL,60153,F,55.0,IL,AM,USAGE UNKNOWN,NOT APPLICABLE,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
1,O2298516,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192153.0,2026-05-06 01:25:00,CHICAGO,IL,60614,M,21.0,IL,D,USAGE UNKNOWN,NOT APPLICABLE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED
2,O2298517,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60617,F,22.0,IL,D,USAGE UNKNOWN,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
3,P505529,PASSENGER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60620,F,NaN,NaN,NaN,USAGE UNKNOWN,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN
4,O2298528,DRIVER,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,2192164.0,2026-05-06 00:48:00,CHICAGO,IL,60647,M,35.0,IL,D,USAGE UNKNOWN,"DEPLOYED, FRONT","REPORTED, NOT EVIDENT",NaN,NaN,NaN,TEST NOT OFFERED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277358,P230379,PASSENGER,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,964731.0,2021-01-01 00:05:00,NaN,NaN,NaN,M,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN
1277359,O1017884,DRIVER,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,964732.0,2021-01-01 00:04:00,NaN,NaN,NaN,X,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED
1277360,O1019428,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966223.0,2021-01-01 00:00:00,CHICAGO,IL,60618,M,24.0,IL,D,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NORMAL,TEST NOT OFFERED
1277361,O1019429,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CICERO,IL,60804,F,23.0,IL,D,SAFETY BELT USED,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
1277362,P230706,PASSENGER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CHICAGO,IL,NaN,M,24.0,NaN,NaN,SAFETY BELT USED,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN

In [58]:
resp = requests.get(
    "https://data.cityofchicago.org/resource/85ca-t3if.csv",
    params={"$where": "crash_date >= '2021-01-01T00:00:00'", "$limit": 700000},
    timeout=300
)
df2 = pd.read_csv(io.StringIO(resp.text))
sha256_crashes = hashlib.sha256(resp.content).hexdigest()
print(f"SHA-256 (Crashes): {sha256_crashes}")
df2

SHA-256 (Crashes): 120b54d1e654643e6fe9790bc41d1017df8c9aae6d679a0e938a8718d3a3e66f

,crash_record_id,crash_date_est_i,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,NaN,2026-05-06T01:26:00.000,25,NO CONTROLS,UNKNOWN,CLEAR,DARKNESS,FIXED OBJECT,NOT DIVIDED,...,0.0,0.0,1.0,0.0,1,4,5,41.873151,-87.739639,POINT (-87.739638646357 41.873150835074)
1,81541975ccbc209299cb226e6953a0531111a9e7d40640...,NaN,2026-05-06T01:25:00.000,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,DIVIDED - W/MEDIAN BARRIER,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
2,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,NaN,2026-05-06T00:48:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,FOUR WAY,...,0.0,3.0,0.0,0.0,0,4,5,41.880995,-87.701059,POINT (-87.701059473296 41.880995041378)
3,82569db581134909bd54cc09f5d0ebce3fc0f8a0d4e703...,NaN,2026-05-05T22:05:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,T-INTERSECTION,...,0.0,0.0,2.0,0.0,22,3,5,41.867623,-87.620332,POINT (-87.62033239926 41.867623428526)
4,0d89d5844d62c46de7ca1450f97f26d7fac6221c7a224a...,NaN,2026-05-05T21:58:00.000,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN BARRIER,...,0.0,0.0,3.0,0.0,21,3,5,41.707406,-87.642702,POINT (-87.642701630639 41.707405500169)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585412,90e627d390edd0adcfb35bfcc5c12c7eeafa68d04b66d0...,NaN,2021-01-01T00:10:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,2.0,0.0,0,6,1,41.812153,-87.684680,POINT (-87.68468042746 41.812153033185)
585413,4ef013035e1af1eb9ea11f83a1251e7ee80b5e35e916d9...,NaN,2021-01-01T00:05:00.000,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,NOT DIVIDED,...,1.0,0.0,1.0,0.0,0,6,1,42.007271,-87.673711,POINT (-87.673710862369 42.007270860381)
585414,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,NaN,2021-01-01T00:05:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,2.0,0.0,0,6,1,41.903129,-87.686909,POINT (-87.686909128207 41.903128739116)
585415,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,NaN,2021-01-01T00:04:00.000,10,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,OTHER,...,0.0,0.0,1.0,0.0,0,6,1,41.937369,-87.707427,POINT (-87.707427053603 41.937368594943)
585416,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,NaN,2021-01-01T00:00:00.000,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,UNKNOWN,UNKNOWN,ANGLE,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)

In [59]:
print(f"Shape: {df2.shape}")
df2.describe(include="number").T

Shape: (585417, 48)

,count,mean,std,min,25%,50%,75%,max
posted_speed_limit,585417.0,28.520900,5.617710,0.000000,30.000000,30.000000,30.000000,70.00000
lane_cnt,74.0,2.621622,1.477713,0.000000,2.000000,2.000000,4.000000,8.00000
street_no,585417.0,3724.958300,2837.434858,0.000000,1333.000000,3232.000000,5559.000000,13799.00000
beat_of_occurrence,585417.0,1253.988099,701.384757,111.000000,725.000000,1213.000000,1822.000000,6100.00000
num_units,585417.0,2.037155,0.456430,1.000000,2.000000,2.000000,2.000000,18.00000
injuries_total,584093.0,0.216478,0.601741,0.000000,0.000000,0.000000,0.000000,21.00000
injuries_fatal,584093.0,0.001222,0.037813,0.000000,0.000000,0.000000,0.000000,4.00000
injuries_incapacitating,584093.0,0.018812,0.160195,0.000000,0.000000,0.000000,0.000000,10.00000
injuries_non_incapacitating,584093.0,0.119601,0.443397,0.000000,0.000000,0.000000,0.000000,19.00000
injuries_reported_not_evident,584093.0,0.076842,0.357542,0.000000,0.000000,0.000000,0.000000,19.00000
injuries_no_indication,584093.0,1.966370,1.130480,0.000000,1.000000,2.000000,2.000000,49.00000
injuries_unknown,584093.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
crash_hour,585417.0,13.154445,5.632655,0.000000,9.000000,14.000000,17.000000,23.00000
crash_day_of_week,585417.0,4.110547,1.982463,1.000000,2.000000,4.000000,6.000000,7.00000
crash_month,585417.0,6.376602,3.404056,1.000000,3.000000,6.000000,9.000000,12.00000
latitude,579867.0,41.854645,0.366603,0.000000,41.784101,41.874301,41.925191,42.02278
longitude,579867.0,-87.673427,0.748541,-87.939678,-87.722324,-87.675532,-87.634715,0.00000

In [60]:
df2[["weather_condition", "lighting_condition"]].value_counts().head(20)

weather_condition  lighting_condition
CLEAR              DAYLIGHT                  311013
                   DARKNESS, LIGHTED ROAD    100553
UNKNOWN            UNKNOWN                    28023
RAIN               DAYLIGHT                   23910
CLEAR              DARKNESS                   18484
RAIN               DARKNESS, LIGHTED ROAD     14737
CLOUDY/OVERCAST    DAYLIGHT                   13769
CLEAR              DUSK                       11559
SNOW               DAYLIGHT                   10070
UNKNOWN            DAYLIGHT                    8943
CLEAR              DAWN                        6891
SNOW               DARKNESS, LIGHTED ROAD      5931
CLEAR              UNKNOWN                     5443
UNKNOWN            DARKNESS, LIGHTED ROAD      4782
RAIN               DARKNESS                    2953
CLOUDY/OVERCAST    DARKNESS, LIGHTED ROAD      1855
RAIN               DUSK                        1742
UNKNOWN            DARKNESS                    1727
SNOW               DARKNESS                    1335
RAIN               DAWN                        1269
Name: count, dtype: int64

In [61]:
df2 = df2.replace(["UNKNOWN", "NONE", ""], pd.NA)

In [62]:
df.isna().mean().sort_values(ascending=False)

driver_action            0.694815
driver_vision            0.635907
drivers_license_class    0.541623
physical_condition       0.491983
drivers_license_state    0.417901
zipcode                  0.329679
age                      0.294679
city                     0.284665
state                    0.267561
bac_result               0.200122
vehicle_id               0.021847
airbag_deployed          0.021117
sex                      0.019028
safety_equipment         0.002585
injury_classification    0.000197
person_type              0.000000
crash_date               0.000000
crash_record_id          0.000000
person_id                0.000000
dtype: float64

In [63]:
df2.columns = df2.columns.str.lower()

In [64]:
df2["crash_record_id"] = df2["crash_record_id"].astype(str)
df2["crash_date"] = pd.to_datetime(df2["crash_date"], errors="coerce")

In [65]:
df

,person_id,person_type,crash_record_id,vehicle_id,crash_date,city,state,zipcode,sex,age,drivers_license_state,drivers_license_class,safety_equipment,airbag_deployed,injury_classification,driver_action,driver_vision,physical_condition,bac_result
0,O2298523,DRIVER,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,2192156.0,2026-05-06 01:26:00,MAYWOOD,IL,60153,F,55.0,IL,AM,USAGE UNKNOWN,NOT APPLICABLE,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
1,O2298516,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192153.0,2026-05-06 01:25:00,CHICAGO,IL,60614,M,21.0,IL,D,USAGE UNKNOWN,NOT APPLICABLE,NO INDICATION OF INJURY,FAILED TO YIELD,NOT OBSCURED,NORMAL,TEST NOT OFFERED
2,O2298517,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60617,F,22.0,IL,D,USAGE UNKNOWN,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
3,P505529,PASSENGER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60620,F,NaN,NaN,NaN,USAGE UNKNOWN,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN
4,O2298528,DRIVER,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,2192164.0,2026-05-06 00:48:00,CHICAGO,IL,60647,M,35.0,IL,D,USAGE UNKNOWN,"DEPLOYED, FRONT","REPORTED, NOT EVIDENT",NaN,NaN,NaN,TEST NOT OFFERED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277358,P230379,PASSENGER,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,964731.0,2021-01-01 00:05:00,NaN,NaN,NaN,M,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN
1277359,O1017884,DRIVER,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,964732.0,2021-01-01 00:04:00,NaN,NaN,NaN,X,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NaN,TEST NOT OFFERED
1277360,O1019428,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966223.0,2021-01-01 00:00:00,CHICAGO,IL,60618,M,24.0,IL,D,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NO INDICATION OF INJURY,NaN,NaN,NORMAL,TEST NOT OFFERED
1277361,O1019429,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CICERO,IL,60804,F,23.0,IL,D,SAFETY BELT USED,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NOT OBSCURED,NORMAL,TEST NOT OFFERED
1277362,P230706,PASSENGER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CHICAGO,IL,NaN,M,24.0,NaN,NaN,SAFETY BELT USED,DID NOT DEPLOY,NO INDICATION OF INJURY,NaN,NaN,NaN,NaN

In [66]:
df2 = df2.dropna(subset=["crash_date"])
df2 = df2[df2["crash_date"] >= "2021-01-01"]
df2

,crash_record_id,crash_date_est_i,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,NaN,2026-05-06 01:26:00,25,NO CONTROLS,NaN,CLEAR,DARKNESS,FIXED OBJECT,NOT DIVIDED,...,0.0,0.0,1.0,0.0,1,4,5,41.873151,-87.739639,POINT (-87.739638646357 41.873150835074)
1,81541975ccbc209299cb226e6953a0531111a9e7d40640...,NaN,2026-05-06 01:25:00,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,DIVIDED - W/MEDIAN BARRIER,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
2,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,NaN,2026-05-06 00:48:00,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,FOUR WAY,...,0.0,3.0,0.0,0.0,0,4,5,41.880995,-87.701059,POINT (-87.701059473296 41.880995041378)
3,82569db581134909bd54cc09f5d0ebce3fc0f8a0d4e703...,NaN,2026-05-05 22:05:00,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,T-INTERSECTION,...,0.0,0.0,2.0,0.0,22,3,5,41.867623,-87.620332,POINT (-87.62033239926 41.867623428526)
4,0d89d5844d62c46de7ca1450f97f26d7fac6221c7a224a...,NaN,2026-05-05 21:58:00,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN BARRIER,...,0.0,0.0,3.0,0.0,21,3,5,41.707406,-87.642702,POINT (-87.642701630639 41.707405500169)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585412,90e627d390edd0adcfb35bfcc5c12c7eeafa68d04b66d0...,NaN,2021-01-01 00:10:00,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,2.0,0.0,0,6,1,41.812153,-87.684680,POINT (-87.68468042746 41.812153033185)
585413,4ef013035e1af1eb9ea11f83a1251e7ee80b5e35e916d9...,NaN,2021-01-01 00:05:00,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,NOT DIVIDED,...,1.0,0.0,1.0,0.0,0,6,1,42.007271,-87.673711,POINT (-87.673710862369 42.007270860381)
585414,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,NaN,2021-01-01 00:05:00,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,2.0,0.0,0,6,1,41.903129,-87.686909,POINT (-87.686909128207 41.903128739116)
585415,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,NaN,2021-01-01 00:04:00,10,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,OTHER,...,0.0,0.0,1.0,0.0,0,6,1,41.937369,-87.707427,POINT (-87.707427053603 41.937368594943)
585416,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,NaN,2021-01-01 00:00:00,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,NaN,NaN,ANGLE,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)

In [67]:
dfm = df.merge(df2, on="crash_record_id", how="left")
dfm

,person_id,person_type,crash_record_id,vehicle_id,crash_date_x,city,state,zipcode,sex,age,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,O2298523,DRIVER,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,2192156.0,2026-05-06 01:26:00,MAYWOOD,IL,60153,F,55.0,...,0.0,0.0,1.0,0.0,1,4,5,41.873151,-87.739639,POINT (-87.739638646357 41.873150835074)
1,O2298516,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192153.0,2026-05-06 01:25:00,CHICAGO,IL,60614,M,21.0,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
2,O2298517,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60617,F,22.0,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
3,P505529,PASSENGER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60620,F,NaN,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
4,O2298528,DRIVER,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,2192164.0,2026-05-06 00:48:00,CHICAGO,IL,60647,M,35.0,...,0.0,3.0,0.0,0.0,0,4,5,41.880995,-87.701059,POINT (-87.701059473296 41.880995041378)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277358,P230379,PASSENGER,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,964731.0,2021-01-01 00:05:00,NaN,NaN,NaN,M,NaN,...,0.0,0.0,2.0,0.0,0,6,1,41.903129,-87.686909,POINT (-87.686909128207 41.903128739116)
1277359,O1017884,DRIVER,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,964732.0,2021-01-01 00:04:00,NaN,NaN,NaN,X,NaN,...,0.0,0.0,1.0,0.0,0,6,1,41.937369,-87.707427,POINT (-87.707427053603 41.937368594943)
1277360,O1019428,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966223.0,2021-01-01 00:00:00,CHICAGO,IL,60618,M,24.0,...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)
1277361,O1019429,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CICERO,IL,60804,F,23.0,...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)
1277362,P230706,PASSENGER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CHICAGO,IL,NaN,M,24.0,...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)

In [68]:
dfm = dfm.drop_duplicates()
dfm

,person_id,person_type,crash_record_id,vehicle_id,crash_date_x,city,state,zipcode,sex,age,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,O2298523,DRIVER,4a1895431cd45c6be4bdd48d0583a977a67f094afd823e...,2192156.0,2026-05-06 01:26:00,MAYWOOD,IL,60153,F,55.0,...,0.0,0.0,1.0,0.0,1,4,5,41.873151,-87.739639,POINT (-87.739638646357 41.873150835074)
1,O2298516,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192153.0,2026-05-06 01:25:00,CHICAGO,IL,60614,M,21.0,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
2,O2298517,DRIVER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60617,F,22.0,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
3,P505529,PASSENGER,81541975ccbc209299cb226e6953a0531111a9e7d40640...,2192154.0,2026-05-06 01:25:00,CHICAGO,IL,60620,F,NaN,...,0.0,0.0,3.0,0.0,1,4,5,41.730741,-87.643612,POINT (-87.643612277572 41.730741396308)
4,O2298528,DRIVER,7fa25d661b77b96a0f68ed7f17e46023f6c07d00fb6d20...,2192164.0,2026-05-06 00:48:00,CHICAGO,IL,60647,M,35.0,...,0.0,3.0,0.0,0.0,0,4,5,41.880995,-87.701059,POINT (-87.701059473296 41.880995041378)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277358,P230379,PASSENGER,a5b59fe5f189da9d69e493fca558f3f7e9fa7e2e5a17f8...,964731.0,2021-01-01 00:05:00,NaN,NaN,NaN,M,NaN,...,0.0,0.0,2.0,0.0,0,6,1,41.903129,-87.686909,POINT (-87.686909128207 41.903128739116)
1277359,O1017884,DRIVER,3b41d999ce80890d8825d8d46ee98570ab1e9c79a0001e...,964732.0,2021-01-01 00:04:00,NaN,NaN,NaN,X,NaN,...,0.0,0.0,1.0,0.0,0,6,1,41.937369,-87.707427,POINT (-87.707427053603 41.937368594943)
1277360,O1019428,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966223.0,2021-01-01 00:00:00,CHICAGO,IL,60618,M,24.0,...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)
1277361,O1019429,DRIVER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CICERO,IL,60804,F,23.0,...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)
1277362,P230706,PASSENGER,1448e416d21b7c264b758414a1c2aa86995e8a297f3159...,966232.0,2021-01-01 00:00:00,CHICAGO,IL,NaN,M,24.0,...,0.0,0.0,3.0,0.0,0,6,1,41.944745,-87.706314,POINT (-87.706314298452 41.944745276013)

In [69]:
dfm["crash_record_id"].isna().sum()

np.int64(0)

In [70]:
# Any injury
dfm["any_injury"] = (
    (dfm["injuries_non_incapacitating"] > 0) |
    (dfm["injuries_incapacitating"] > 0) |
    (dfm["injuries_fatal"] > 0)
).astype(int)

# Severe only
dfm["severe_injury"] = (
    (dfm["injuries_incapacitating"] > 0) |
    (dfm["injuries_fatal"] > 0)
).astype(int)

In [71]:
df2 = dfm.groupby("crash_record_id").agg({
    "any_injury": "max",
    "person_id": "count",
    "posted_speed_limit": "first",
    "weather_condition": "first",
    "lighting_condition": "first",
    "traffic_control_device": "first",
    "roadway_surface_cond": "first",
    "crash_hour": "first",
    "crash_day_of_week": "first",
    "crash_month": "first",
    "latitude": "first",
    "longitude": "first"
}).rename(columns={
    "person_id": "num_people"
}).reset_index()

In [72]:
df2["weather_group"] = df2["weather_condition"].replace({
    "CLEAR": "CLEAR",
    "CLOUDY/OVERCAST": "CLEAR",
    "RAIN": "BAD",
    "SNOW": "BAD",
    "FOG/SMOKE/HAZE": "BAD",
    "SLEET/HAIL": "BAD",
    "FREEZING RAIN/DRIZZLE": "BAD",
    "BLOWING SNOW": "BAD",
    "BLOWING SAND, SOIL, DIRT": "BAD"
})

In [73]:
df2["lighting_group"] = df2["lighting_condition"].replace({
    "DAYLIGHT": "DAY",
    "DARKNESS": "NIGHT",
    "DARKNESS, LIGHTED ROAD": "NIGHT",
    "DUSK": "LOW_LIGHT",
    "DAWN": "LOW_LIGHT"
})

In [74]:
df2["speed_bin"] = pd.cut(
    df2["posted_speed_limit"],
    bins=[0, 25, 35, 45, 100],
    labels=["LOW", "MEDIUM", "HIGH", "VERY_HIGH"]
)

In [75]:
df2["is_night"] = df2["crash_hour"].isin([20,21,22,23,0,1,2,3,4,5])

In [76]:
df2.groupby("weather_group")["any_injury"].mean()

weather_group
BAD                       0.114698
CLEAR                     0.109515
OTHER                     0.111888
SEVERE CROSS WIND GATE    0.112676
Name: any_injury, dtype: float64

In [77]:
df2.groupby("lighting_group")["any_injury"].mean()

lighting_group
DAY          0.098339
LOW_LIGHT    0.120087
NIGHT        0.133921
Name: any_injury, dtype: float64

In [78]:
df2.groupby("speed_bin")["any_injury"].mean()

speed_bin
LOW          0.065945
MEDIUM       0.112111
HIGH         0.147600
VERY_HIGH    0.138090
Name: any_injury, dtype: float64

In [79]:
from sklearn.linear_model import LogisticRegression

X = pd.get_dummies(df2[[
    "posted_speed_limit",
    "weather_group",
    "lighting_group",
    "is_night"
]], drop_first=True)

y = df2["any_injury"]

model = LogisticRegression(max_iter=1000)
model.fit(X, y)

LogisticRegression(max_iter=1000)

In [80]:
injutry_prob = model.predict_proba(X)[:, 1]
injutry_prob

array([0.10048012, 0.10048012, 0.06703627, ..., 0.13344237, 0.15024812,
       0.09921139], shape=(584093,))

In [81]:
predict = model.predict(X)
predict

array([0, 0, 0, ..., 0, 0, 0], shape=(584093,))

In [82]:
from sklearn.metrics import accuracy_score, roc_auc_score

accuracy = accuracy_score(y, predict)
auc = roc_auc_score(y, injutry_prob)

accuracy, auc

(0.8957032527354377, 0.5865980554382288)

In [83]:
dfm.to_csv(data_dir / "merged_dataset.csv", index=False)
df2.to_csv(data_dir / "crashes_dataset.csv", index=False)
df.to_csv(data_dir / "people_dataset.csv", index=False)

In [84]:
resp = requests.get(
    "https://data.cityofchicago.org/resource/hhkd-xvj4.csv",
    params={"$where": "violation_date >= '2021-01-01T00:00:00'", "$limit": 300000},
    timeout=300
)
df_cam = pd.read_csv(io.StringIO(resp.text), low_memory=False)
print(f"Shape: {df_cam.shape}")
sha256_camera = hashlib.sha256(resp.content).hexdigest()
print(f"SHA-256 (Speed Camera): {sha256_camera}")
df_cam.head()

Shape: (235284, 9)
SHA-256 (Speed Camera): e8b585b6852ccc4c13208cd3a314c21604b040e2efc931ea3494e3bd7ff9da8f

,address,camera_id,violation_date,violations,x_coordinate,y_coordinate,latitude,longitude,location
0,1110 S PULASKI RD,CHI163,2026-04-01T00:00:00.000,9.0,1.149841e+06,1.894931e+06,41.867603,-87.725383,"\n, \n(41.86760272243294, -87.7253827433152)"
1,11153 S VINCENNES,CHI022,2026-04-01T00:00:00.000,21.0,1.167029e+06,1.830594e+06,41.690702,-87.664122,"\n, \n(41.690701951255015, -87.66412238501842)"
2,1117 S PULASKI RD,CHI162,2026-04-01T00:00:00.000,6.0,1.149923e+06,1.894858e+06,41.867402,-87.725084,"\n, \n(41.867401834997956, -87.72508368792016)"
3,1226 N WESTERN AVE,CHI128,2026-04-01T00:00:00.000,4.0,1.160143e+06,1.908203e+06,41.903817,-87.687195,"\n, \n(41.90381710275111, -87.6871949977686)"
4,1229 N WESTERN AVE,CHI127,2026-04-01T00:00:00.000,4.0,1.160223e+06,1.908226e+06,41.903878,-87.686903,"\n, \n(41.90387807933294, -87.68690274176198)"

In [85]:
df_cam.isna().mean().sort_values(ascending=False)

x_coordinate      0.032331
y_coordinate      0.032331
latitude          0.032331
longitude         0.032331
location          0.032331
camera_id         0.000021
address           0.000000
violation_date    0.000000
violations        0.000000
dtype: float64

In [86]:
df_cam.describe(include="number")

          violations  x_coordinate  y_coordinate       latitude      longitude
count  235284.000000  2.276770e+05  2.276770e+05  227677.000000  227677.000000
mean       56.458871  1.159062e+06  1.894397e+06      41.865938     -87.691592
std        71.882697  1.664516e+04  3.230105e+04       0.088832       0.060595
min         1.000000  1.121638e+06  1.820629e+06      41.663174     -87.828317
25%        14.000000  1.149006e+06  1.868012e+06      41.793493     -87.728050
50%        34.000000  1.158989e+06  1.900735e+06      41.883192     -87.690933
75%        69.000000  1.168211e+06  1.922706e+06      41.944319     -87.658573
max      1888.000000  1.203645e+06  1.947791e+06      42.012316     -87.529848

In [87]:
df_cam = df_cam.replace(["UNKNOWN", "NONE", ""], pd.NA)
df_cam = df_cam.drop(columns=[c for c in df_cam.columns if df_cam[c].isna().mean() > 0.8])
df_cam.columns = df_cam.columns.str.lower()
df_cam["violation_date"] = pd.to_datetime(df_cam["violation_date"], errors="coerce")
df_cam = df_cam.dropna(subset=["violation_date"])
df_cam = df_cam[df_cam["violation_date"] >= "2021-01-01"]
df_cam

,address,camera_id,violation_date,violations,x_coordinate,y_coordinate,latitude,longitude,location
0,1110 S PULASKI RD,CHI163,2026-04-01,9.0,1.149841e+06,1.894931e+06,41.867603,-87.725383,"\n, \n(41.86760272243294, -87.7253827433152)"
1,11153 S VINCENNES,CHI022,2026-04-01,21.0,1.167029e+06,1.830594e+06,41.690702,-87.664122,"\n, \n(41.690701951255015, -87.66412238501842)"
2,1117 S PULASKI RD,CHI162,2026-04-01,6.0,1.149923e+06,1.894858e+06,41.867402,-87.725084,"\n, \n(41.867401834997956, -87.72508368792016)"
3,1226 N WESTERN AVE,CHI128,2026-04-01,4.0,1.160143e+06,1.908203e+06,41.903817,-87.687195,"\n, \n(41.90381710275111, -87.6871949977686)"
4,1229 N WESTERN AVE,CHI127,2026-04-01,4.0,1.160223e+06,1.908226e+06,41.903878,-87.686903,"\n, \n(41.90387807933294, -87.68690274176198)"
...,...,...,...,...,...,...,...,...,...
235279,8006 W ADDISON ST,CHI176,2021-01-01,4.0,1.122009e+06,1.923002e+06,41.945129,-87.826952,"\n, \n(41.945129353961654, -87.8269516993975)"
235280,8020 W FOREST PRESERVE AV,CHI174,2021-01-01,26.0,1.121895e+06,1.922706e+06,41.944319,-87.827378,"\n, \n(41.944318833069445, -87.8273782786742)"
235281,8318 S ASHLAND AVE,CHI169,2021-01-01,29.0,1.167083e+06,1.849460e+06,41.742474,-87.663385,"\n, \n(41.74247385456547, -87.66338547998558)"
235282,8345 S ASHLAND AVE,CHI168,2021-01-01,33.0,1.167170e+06,1.849194e+06,41.741742,-87.663073,"\n, \n(41.741741651401504, -87.66307332925098)"
235283,9618 S EWING AVE,CHI142,2021-01-01,6.0,1.202075e+06,1.841845e+06,41.720757,-87.535437,"\n, \n(41.72075680558273, -87.53543678735923)"

In [88]:
df_cam.isna().mean().sort_values(ascending=False)

x_coordinate      0.032331
y_coordinate      0.032331
latitude          0.032331
longitude         0.032331
location          0.032331
camera_id         0.000021
address           0.000000
violation_date    0.000000
violations        0.000000
dtype: float64

In [89]:
sample_date = df_cam["violation_date"].dt.date.mode()[0]
n_crashes = (dfm["crash_date_x"].dt.date == sample_date).sum()
n_cam = (df_cam["violation_date"].dt.date == sample_date).sum()
print(f"Sample date: {sample_date}")
print(f"  Crash person records on that date: {n_crashes}")
print(f"  Camera records on that date: {n_cam}")
print(f"  Date-joined rows would be: {n_crashes * n_cam}")
print("\nNo shared row-level key between datasets.")
print("Speed camera data profiled and cleaned but excluded from model integration.")

Sample date: 2026-02-25
  Crash person records on that date: 700
  Camera records on that date: 208
  Date-joined rows would be: 145600

No shared row-level key between datasets.
Speed camera data profiled and cleaned but excluded from model integration.

In [90]:
df_cam.to_csv(data_dir / "speed_camera_violations.csv", index=False)